In [1]:
import tensorflow as tf

# Create two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix1, matrix2)  # Alternatively, use tf.linalg.matmul
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [2]:
# Inputs (X), Weights (W), and Bias (b)
X = tf.constant([[1.0, 2.0, 3.0]])  # 1 sample with 3 features
W = tf.constant([[0.2, 0.8], [0.5, 0.3], [0.9, 0.7]])  # Weight matrix (3x2)
b = tf.constant([0.1, 0.2])  # Bias vector (1x2)

# Feed-forward computation
Z = tf.matmul(X, W) + b  # Weighted sum
output = tf.nn.relu(Z)   # Apply ReLU activation
print("Output of Feed-Forward Pass:\n", output)


Output of Feed-Forward Pass:
 tf.Tensor([[4.  3.7]], shape=(1, 2), dtype=float32)


In [3]:
# Inputs (X)
X = tf.constant([[1.0, 2.0, 3.0]])  # 1 sample with 3 features

# Weights and Biases for Layer 1
W1 = tf.constant([[0.2, 0.8], [0.5, 0.3], [0.9, 0.7]])
b1 = tf.constant([0.1, 0.2])

# Weights and Biases for Layer 2
W2 = tf.constant([[0.4, 0.6], [0.1, 0.5]])
b2 = tf.constant([0.3, 0.7])

# Layer 1 computation
Z1 = tf.matmul(X, W1) + b1
A1 = tf.nn.relu(Z1)

# Layer 2 computation
Z2 = tf.matmul(A1, W2) + b2
output = tf.nn.softmax(Z2)  # Apply softmax activation for output
print("Final Output:\n", output)


Final Output:
 tf.Tensor([[0.06416388 0.9358361 ]], shape=(1, 2), dtype=float32)
