In [1]:
import tensorflow as tf

# Create a variable
x = tf.Variable([1, 2, 3], dtype=tf.int32)
print("Variable x:", x)
print("Shape of x:", x.shape)


Variable x: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
Shape of x: (3,)


In [2]:
# Initialize a variable
v = tf.Variable(5.0)

# Update the variable using the assign() method
v.assign(10.0)
print("Updated value of v:", v.numpy())

# Increment the variable
v.assign_add(2.0)
print("After incrementing:", v.numpy())

# Decrement the variable
v.assign_sub(1.0)
print("After decrementing:", v.numpy())


Updated value of v: 10.0
After incrementing: 12.0
After decrementing: 11.0


In [3]:
# Create variables
a = tf.Variable(3.0)
b = tf.Variable(4.0)

# Perform mathematical operations
c = a * b + 2
print("Result of the operation (a * b + 2):", c.numpy())


Result of the operation (a * b + 2): 14.0


In [4]:
# Create a variable with random initial values
random_var = tf.Variable(tf.random.normal([3, 3], mean=0, stddev=1))
print("Random Variable:")
print(random_var)


Random Variable:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.07550723, -1.0993941 ,  0.08975922],
       [-0.89404416, -0.16828243,  1.5100111 ],
       [ 0.45560893,  0.4065426 , -0.8845627 ]], dtype=float32)>


In [5]:
# Weight and bias initialization for a model
weights = tf.Variable(tf.random.truncated_normal([4, 3], stddev=0.1))
biases = tf.Variable(tf.zeros([3]))

print("Weights:", weights.numpy())
print("Biases:", biases.numpy())


Weights: [[ 0.08837797  0.06653269 -0.05227363]
 [-0.0784269   0.09340575  0.04862134]
 [-0.02380584  0.03728146  0.09480881]
 [-0.04674436 -0.10593068 -0.04791727]]
Biases: [0. 0. 0.]
