In [3]:
!pip install tensorflow

  Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
  Using cached tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.12.23-py2.py3-none-any.whl.metadata (876 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached grpcio-1.69.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached keras-3.8.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached ml_dtypes-0.4.1-cp312-cp312-win_amd64.whl.metadata (20 kB)
  Using

In [5]:
import tensorflow as tf

# Print TensorFlow version
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [7]:
import tensorflow as tf

# Create a 1D tensor
tensor_1d = tf.constant([1, 2, 3, 4, 5])
print("1D Tensor:", tensor_1d)

# Create a 2D tensor
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print("\n2D Tensor:")
print(tensor_2d)

# Perform operations on tensors
# Add two tensors
tensor_sum = tf.add(tensor_2d, 2)
print("\nTensor after addition:")
print(tensor_sum)

# Multiply tensors element-wise
tensor_mul = tf.multiply(tensor_2d, 2)
print("\nTensor after element-wise multiplication:")
print(tensor_mul)

# Matrix multiplication
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
tensor_matmul = tf.matmul(matrix1, matrix2)
print("\nTensor after matrix multiplication:")
print(tensor_matmul)

# Get the shape and datatype of a tensor
print("\nShape of 2D Tensor:", tensor_2d.shape)
print("Data type of 2D Tensor:", tensor_2d.dtype)


1D Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

2D Tensor:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Tensor after addition:
tf.Tensor(
[[3 4]
 [5 6]
 [7 8]], shape=(3, 2), dtype=int32)

Tensor after element-wise multiplication:
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)

Tensor after matrix multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

Shape of 2D Tensor: (3, 2)
Data type of 2D Tensor: <dtype: 'int32'>
