In [1]:
import tensorflow as tf

# Create a tensor with 12 elements
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape to a 2D tensor (3 rows, infer columns)
reshaped_tensor = tf.reshape(tensor, [3, -1])  # -1 will calculate columns
print("Reshaped Tensor (3x4):\n", reshaped_tensor)


Reshaped Tensor (3x4):
 tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [2]:
# Create a 2D tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
flattened_tensor = tf.reshape(tensor, [-1])
print("Flattened Tensor:", flattened_tensor)


Flattened Tensor: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [3]:
# Create a tensor with 24 elements
tensor = tf.constant([i for i in range(1, 25)])  # Tensor: [1, 2, ..., 24]

# Reshape to (2, 3, 4) using -1
reshaped_tensor = tf.reshape(tensor, [2, 3, -1])  # -1 will infer the last dimension
print("Reshaped Tensor (2x3x4):\n", reshaped_tensor)


Reshaped Tensor (2x3x4):
 tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [4]:
# Create a tensor with 10 elements
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Attempt to reshape to (3, -1) (incompatible shape)
try:
    reshaped_tensor = tf.reshape(tensor, [3, -1])
except Exception as e:
    print("Error:", e)


Error: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 10 values, but the requested shape requires a multiple of 3 [Op:Reshape]


In [5]:
# Create a tensor with 36 elements
tensor = tf.constant([i for i in range(36)])

# Reshape to (3, -1, 6) - Let TensorFlow infer the second dimension
reshaped_tensor = tf.reshape(tensor, [3, -1, 6])  # 3 rows, inferred columns, 6 depth
print("Reshaped Tensor (3x2x6):\n", reshaped_tensor)


Reshaped Tensor (3x2x6):
 tf.Tensor(
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]], shape=(3, 2, 6), dtype=int32)
