**Data Pre Processing- Iris**

**Import libraries**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**import dataset**

In [ ]:
dataset = pd.read_csv('iris.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

print dataset

In [ ]:
print(dataset)

    sepal.length  sepal.width  petal.length  petal.width     variety
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            5.8          4.0           1.2          0.2      Setosa
4            5.7          4.4           1.5          0.4      Setosa
5            5.4          3.4           1.7          0.2      Setosa
6            5.1          3.7           1.5          0.4      Setosa
7            4.6          3.6           1.0          0.2      Setosa
8            5.1          3.3           1.7          0.5      Setosa
9            4.8          3.4           1.9          0.2      Setosa
10           5.0          3.0           1.6          0.2      Setosa
11           5.0          3.4           1.6          0.4      Setosa
12           5.2          NaN           1.5          0.2      Setosa
13           5.1          3.8     

**print x that is converted into array**

In [ ]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 nan 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.8 3.2 5.

**print y that is converted into 1D Numpy array**

In [ ]:
print(y)

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Virginica'
 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica'
 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica'
 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica']


**handle the missing data**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:2])
x[:,1:2] = imputer.transform(x[:,1:2])

print the new array x

In [ ]:
print(x)

[[5.1       3.5       1.4       0.2      ]
 [4.9       3.        1.4       0.2      ]
 [4.7       3.2       1.3       0.2      ]
 [5.8       4.        1.2       0.2      ]
 [5.7       4.4       1.5       0.4      ]
 [5.4       3.4       1.7       0.2      ]
 [5.1       3.7       1.5       0.4      ]
 [4.6       3.6       1.        0.2      ]
 [5.1       3.3       1.7       0.5      ]
 [4.8       3.4       1.9       0.2      ]
 [5.        3.        1.6       0.2      ]
 [5.        3.4       1.6       0.4      ]
 [5.2       3.0137931 1.5       0.2      ]
 [5.1       3.8       1.6       0.2      ]
 [4.6       3.2       1.4       0.2      ]
 [5.3       3.7       1.5       0.2      ]
 [5.        3.3       1.4       0.2      ]
 [7.        3.2       4.7       1.4      ]
 [6.4       3.2       4.5       1.5      ]
 [6.9       3.1       4.9       1.5      ]
 [5.5       2.3       4.        1.3      ]
 [6.5       2.8       4.6       1.5      ]
 [5.7       2.8       4.5       1.3      ]
 [6.3      

**encoding dependent variable**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print encoded dependent variable

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


**split the data set into training set and test set**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[[5.7       2.9       4.2       1.3      ]
 [6.3       3.3       6.        2.5      ]
 [4.9       2.4       3.3       1.       ]
 [5.        3.        1.6       0.2      ]
 [6.3       2.7       4.9       1.8      ]
 [5.2       2.7       3.9       1.4      ]
 [6.3       2.5       5.        1.9      ]
 [6.1       2.9       4.7       1.4      ]
 [5.8       2.7       5.1       1.9      ]
 [6.7       2.5       5.8       1.8      ]
 [5.        2.        3.5       1.       ]
 [4.9       2.5       4.5       1.7      ]
 [6.2       3.4       5.4       2.3      ]
 [5.6       2.9       3.6       1.3      ]
 [5.1       3.8       1.6       0.2      ]
 [5.7       2.8       4.5       1.3      ]
 [7.7       2.8       6.7       2.       ]
 [5.8       2.6       4.        1.2      ]
 [7.        3.2       4.7       1.4      ]
 [6.7       3.        5.2       2.3      ]
 [5.        2.3       3.3       1.       ]
 [6.3       3.3       4.7       1.6      ]
 [5.7       4.4       1.5       0.4      ]
 [4.6      

In [ ]:
print(x_test)

[[5.6 2.8 4.9 2. ]
 [4.7 3.2 1.3 0.2]
 [5.7 3.  4.2 1.2]
 [7.3 2.9 6.3 1.8]
 [5.7 2.8 4.1 1.3]
 [5.6 2.7 4.2 1.3]
 [5.1 2.5 3.  1.1]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [6.8 3.2 5.9 2.3]
 [6.5 3.  5.8 2.2]
 [5.8 4.  1.2 0.2]]


In [ ]:
print(y_train)

[1 2 1 0 2 1 2 1 2 2 1 2 2 1 0 1 2 1 1 2 1 1 0 0 1 1 2 2 1 2 1 1 0 2 0 2 0
 0 0 0 0 0 0 0 0 2 1]


In [ ]:
print(y_test)

[2 0 1 2 1 1 1 1 1 2 2 0]
