In [ ]:
#Load data

In [ ]:
import json
import pandas as pd

In [ ]:
#load the JSON data

In [ ]:
with open('/content/Sarcasm_Headlines_Dataset.json','r') as f:
  data =[json.loads(line) for line in f]

#convert to dataFrame

df= pd.DataFrame(data)

In [ ]:
df.head()

,is_sarcastic,headline,article_link
0,1,thirtysomething scientists unveil doomsday clo...,https://www.theonion.com/thirtysomething-scien...
1,0,dem rep. totally nails why congress is falling...,https://www.huffingtonpost.com/entry/donna-edw...
2,0,eat your veggies: 9 deliciously different recipes,https://www.huffingtonpost.com/entry/eat-your-...
3,1,inclement weather prevents liar from getting t...,https://local.theonion.com/inclement-weather-p...
4,1,mother comes pretty close to using word 'strea...,https://www.theonion.com/mother-comes-pretty-c...


In [ ]:
#2.Drop artical_link from dataset

In [ ]:
df= df.drop(['article_link'],axis=1)

In [ ]:
df.head()

,is_sarcastic,headline
0,1,thirtysomething scientists unveil doomsday clo...
1,0,dem rep. totally nails why congress is falling...
2,0,eat your veggies: 9 deliciously different recipes
3,1,inclement weather prevents liar from getting t...
4,1,mother comes pretty close to using word 'strea...


In [ ]:
df.columns

Index(['is_sarcastic', 'headline'], dtype='object')

In [ ]:
#3.Get the length of each headline and add a column for that

In [ ]:
df['headline_length']=df['headline'].apply(lambda x:len(x.split()))

In [ ]:
df['headline_length']

,headline_length
0,8
1,13
2,7
3,8
4,9
...,...
28614,7
28615,13
28616,12
28617,8


In [ ]:
#4.Initialize parameter values

In [ ]:
max_features =10000   #no.of words consider from tokenizer
maxlen =25            #max length of each sentence
embedding_size =200   #size of embedding vector


In [ ]:
#5.Apply tokenizer and get indices for words

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
Tokenizer =Tokenizer(num_words=max_features, oov_token='OOV')
Tokenizer.fit_on_texts(df['headline'])
sequences = Tokenizer.texts_to_sequences(df['headline'])

In [ ]:
sequences

[[1, 355, 3167, 7474, 2644, 3, 661, 1119],
 [7475, 1775, 758, 3168, 47, 239, 11, 1844, 1048, 8, 1528, 2154, 1845],
 [863, 33, 1, 262, 1, 647, 1484],
 [1, 1594, 6418, 5665, 16, 143, 2, 152],
 [472, 495, 322, 922, 2, 572, 550, 1, 6419],
 [83, 73, 1],
 [84, 280, 2, 4182, 33, 2515, 10, 573, 1356],
 [1846, 1, 777, 5063, 3169, 1120, 25, 227, 25, 1433, 3, 1434, 3359, 4183],
 [2961, 292, 143, 139, 1709, 2, 425, 5, 1, 1595, 356, 1357],
 [2792, 3, 160, 115, 21, 7476],
 [21, 2645, 11, 3360, 7, 426, 5, 3580, 9, 69, 1006, 43, 15, 26],
 [7477, 1, 648, 60, 536, 201, 11, 1358, 626, 1],
 [35, 2, 115, 1, 1710, 1, 6, 1049],
 [574, 1596, 953, 149, 85, 76, 2, 1776, 6, 9021, 1, 7478, 3, 1149, 3, 1],
 [1529, 4184, 12, 6420, 26, 1530, 1, 8, 9022],
 [1318, 379, 7479, 9023, 5064, 80, 16, 13, 1711, 7480, 2155],
 [50, 433, 1150, 5666, 9, 2156, 2793, 3, 1, 3361],
 [50, 14, 323, 100, 3, 31, 2261, 18, 1],
 [537, 59, 411, 10, 3362, 343],
 [3363, 3581, 2962, 98, 58, 2, 2516, 20, 2, 416, 33, 484, 259],
 [1319, 1712, 39

In [ ]:
df.head(1)

,is_sarcastic,headline,headline_length
0,1,thirtysomething scientists unveil doomsday clo...,8


In [ ]:
#6.Pad sequences and prepare target array

In [ ]:
x= pad_sequences(sequences,maxlen=maxlen,padding='post',truncating='post')
y=df['is_sarcastic'].values

In [ ]:
x

array([[   1,  355, 3167, ...,    0,    0,    0],
       [7475, 1775,  758, ...,    0,    0,    0],
       [ 863,   33,    1, ...,    0,    0,    0],
       ...,
       [   4,  100,  629, ...,    0,    0,    0],
       [1870, 1313, 3317, ...,    0,    0,    0],
       [ 217, 3283,   21, ...,    0,    0,    0]], dtype=int32)

In [ ]:
y

array([1, 0, 0, ..., 0, 1, 1])

In [ ]:
#7.Vocab mapping and setting number of words

In [ ]:
word_index = Tokenizer.word_index
Vocab_size = len(word_index)+1

In [ ]:
word_index

{'OOV': 1,
 'to': 2,
 'of': 3,
 'the': 4,
 'in': 5,
 'for': 6,
 'a': 7,
 'on': 8,
 'and': 9,
 'with': 10,
 'is': 11,
 'new': 12,
 'trump': 13,
 'man': 14,
 'at': 15,
 'from': 16,
 'about': 17,
 'by': 18,
 'after': 19,
 'you': 20,
 'this': 21,
 'out': 22,
 'up': 23,
 'be': 24,
 'as': 25,
 'that': 26,
 'it': 27,
 'how': 28,
 'not': 29,
 'he': 30,
 'his': 31,
 'are': 32,
 'your': 33,
 'just': 34,
 'what': 35,
 'all': 36,
 'who': 37,
 'has': 38,
 'will': 39,
 'report': 40,
 'into': 41,
 'more': 42,
 'one': 43,
 'have': 44,
 'year': 45,
 'over': 46,
 'why': 47,
 'day': 48,
 'u': 49,
 'area': 50,
 'woman': 51,
 'can': 52,
 's': 53,
 'says': 54,
 'donald': 55,
 'time': 56,
 'first': 57,
 'like': 58,
 'no': 59,
 'her': 60,
 'get': 61,
 'off': 62,
 'old': 63,
 "trump's": 64,
 'life': 65,
 'now': 66,
 'people': 67,
 "'": 68,
 'an': 69,
 'house': 70,
 'still': 71,
 'obama': 72,
 'white': 73,
 'back': 74,
 'make': 75,
 'was': 76,
 'than': 77,
 'women': 78,
 'if': 79,
 'down': 80,
 'when': 81,
 'i'

In [ ]:
Vocab_size

30886

In [ ]:
#Load GloVe word Embeddings

In [ ]:
import numpy as np
embeddings_index ={}
with open('/content/glove.6B.50d.txt',encoding='utf-8') as f:
  for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:],dtype='float32')
    embeddings_index[word] =coefs

In [ ]:
coefs

array([-0.43264, -1.0114 ,  0.69846, -0.48718, -0.63683,  0.18958],
      dtype=float32)

In [ ]:
embeddings_index[word]

array([-0.43264, -1.0114 ,  0.69846, -0.48718, -0.63683,  0.18958],
      dtype=float32)

In [ ]:
#9.Create embedding matrix

In [ ]:
#9.Create embedding matrix
embedding_size = 50  # Change embedding_size to 50 to match GloVe embeddings
embedding_matrix = np.zeros((Vocab_size, embedding_size))
for word, i in word_index.items():
    if i < max_features:
        embedding_vector = embeddings_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [ ]:
#10.Define Model

In [ ]:
#9.Create embedding matrix
embedding_size = 50  # Change embedding_size to 50 to match GloVe embeddings
embedding_matrix = np.zeros((max_features, embedding_size)) # Change Vocab_size to max_features
for word, i in word_index.items():
    if i < max_features:
        embedding_vector = embeddings_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [ ]:
#11. Compile the model

In [ ]:
#10.Define Model
from tensorflow import keras
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = keras.Sequential([
    Embedding(max_features, embedding_size, weights=[embedding_matrix], input_length=maxlen, trainable=False),
    LSTM(128),
    Dense(1, activation='sigmoid')  # For binary classification (sarcastic/not sarcastic)
])

#11. Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
#12. Fit the model

In [ ]:
from sklearn.model_selection import train_test_split

# Change 'X' to 'x' to use the padded sequences
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

history = model.fit(X_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(X_test, y_test))

Epoch 1/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 28s 35ms/step - accuracy: 0.6717 - loss: 0.5951 - val_accuracy: 0.8068 - val_loss: 0.4212
Epoch 2/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 41s 36ms/step - accuracy: 0.8050 - loss: 0.4255 - val_accuracy: 0.8145 - val_loss: 0.4055
Epoch 3/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 39s 33ms/step - accuracy: 0.8373 - loss: 0.3760 - val_accuracy: 0.8347 - val_loss: 0.3631
Epoch 4/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 43s 35ms/step - accuracy: 0.8506 - loss: 0.3397 - val_accuracy: 0.8372 - val_loss: 0.3634
Epoch 5/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 40s 34ms/step - accuracy: 0.8700 - loss: 0.3022 - val_accuracy: 0.8531 - val_loss: 0.3370
Epoch 6/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 26s 36ms/step - accuracy: 0.8795 - loss: 0.2802 - val_accuracy: 0.8567 - val_loss: 0.3336
Epoch 7/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 26s 36ms/step - accuracy: 0.8939 - loss: 0.2547 - val_accuracy: 0.8503 - val_loss: 0.3596
Epoch 8/10
716/716 ━━━━━━━━━━━━━━━━━━━━ 25s 35ms/step - accuracy: 0.9088 - loss: 0.2206 - 

In [ ]:

history