In [14]:
import numpy as np
from collections import Counter
from sklearn.decomposition import TruncatedSVD

# Custom corpus
sentences = [
    ["i", "love", "nlp"],
    ["i", "love", "ai"],
    ["nlp", "is", "interesting"],
    ["ai", "is", "powerful"]
]

# Build vocabulary
words = [word for sent in sentences for word in sent]
vocab = list(set(words))
word2id = {w:i for i,w in enumerate(vocab)}

# Build co-occurrence matrix
window = 2
matrix = np.zeros((len(vocab), len(vocab)))

for sent in sentences:
    for idx, word in enumerate(sent):
        for j in range(max(0, idx-window), min(len(sent), idx+window+1)):
            if idx != j:
                matrix[word2id[word]][word2id[sent[j]]] += 1

print("Co-occurrence Matrix:\n", matrix)

# Apply SVD (GloVe-style factorization)
svd = TruncatedSVD(n_components=5)
embeddings = svd.fit_transform(matrix)

# Get vector for 'nlp'
nlp_vector = embeddings[word2id["nlp"]]

print("\nGloVe-style vector for 'nlp':")
print(nlp_vector)

Co-occurrence Matrix:
 [[0. 1. 0. 1. 2. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1.]
 [2. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0.]]

GloVe-style vector for 'nlp':
[1.506597   1.         0.37796447 0.12352304 0.26842203]
